---
# tasks file for db-tier

- name: install PostgreSQL
  package: 
    name: postgresql-server
    state: latest

- name: enable postgresql at boot
  service:
    name: postgresql
    enabled: yes
  notify: start postgres

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: Ensure PostgreSQL database is initialized.
  command: postgresql-setup initdb
  when: not pgdata_dir_version.stat.exists
  notify: start postgres
